version: '3'

services:
  vim:
    container_name: vim-dev
    build:
      context: .
      dockerfile: vim.dockerfile
    tty: true
    restart: always
    volumes:
      - ..:/myubuntu
        # - ../MyVM/MyDocker/docker-template-go/code:/root/go/src
        # - ../MyVM/MyDocker/ci-cd-test/code:/root/go/src/ci-cd-test
        # - ../MyVM/MyDocker/snippetbox/code:/root/go/src/github.com/hodanov
