version: '3'

services:
  nvim:
    platform: linux/amd64
    container_name: nvim-dev
    build:
      context: .
      dockerfile: nvim.dockerfile
    tty: true
    restart: always
    networks:
      - my-nvim
    volumes:
      - ..:/myubuntu
networks:
  my-nvim:
    driver: bridge
    external: true
