###################
# Color Scheme, status/tabline and so on..
###################

# File manager
[[plugins]]
repo = 'scrooloose/nerdtree'

# Status/tabline
[[plugins]]
repo = 'vim-airline/vim-airline'

# Modify theme of vim-airline
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# Show `git diff` in the gutter(sign column)
[[plugins]]
repo = 'airblade/vim-gitgutter'

# Add indent line
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# Color scheme
[[plugins]]
repo = 'morhetz/gruvbox'

# Docker
# [[plugins]]
# repo = 'ekalinin/Dockerfile.vim'

# Golang
# [[plugins]]
# repo = 'fatih/vim-go'

# Python
# [[plugins]]
# repo = 'hhatto/autopep8'

# HTML/CSS
# [[plugins]]
# repo = 'mattn/emmet-vim'

###################
# Auto complete and linter
###################

# Surroundings: for example parentheses, brackets, quotes, XML tags, and more.
[[plugins]]
repo = 'tpope/vim-surround'

# Asynchronous Lint Engine, error check
# [[plugins]]
# repo = 'dense-analysis/ale'

# Auto complete
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'yami-beta/asyncomplete-omni.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
merged = '0'

[[plugins]]
repo = 'mattn/vim-lsp-icons'

[[plugins]]
repo = 'mattn/vim-goimports'

# Auto complete
# [[plugins]]
# repo = 'neoclide/coc.nvim'
# merge = 0
# rev = 'release'

# Finder
# [[plugins]]
# repo = 'ctrlpvim/ctrlp.vim'

###################
# Auto complete and linter
###################

# Markdown preview
# [[plugins]]
# repo = 'iamcco/markdown-preview.nvim'
# on_ft = ['markdown', 'pandoc.markdown', 'rmd']
# build = '''
# cd app & yarn install
# '''

# Support making a table
# [[plugins]]
# repo = 'mattn/vim-maketable'

# Google translate in vim
# [[plugins]]
# repo = 'skanehira/translate.vim'

