###################
# Color Scheme, status/tabline and so on..
###################

# File manager
[[plugins]]
repo = 'lambdalisue/fern.vim'

# Status/tabline
[[plugins]]
repo = 'vim-airline/vim-airline'

# Modify theme of vim-airline
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# Show `git diff` in the gutter(sign column)
[[plugins]]
repo = 'airblade/vim-gitgutter'

# Add indent line
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# Color scheme
[[plugins]]
repo = 'morhetz/gruvbox'

# Docker
# [[plugins]]
# repo = 'ekalinin/Dockerfile.vim'

# Python
[[plugins]]
repo = 'hhatto/autopep8'

# HTML/CSS
# [[plugins]]
# repo = 'mattn/emmet-vim'

# Terraform
[[plugins]]
repo = 'hashivim/vim-terraform'

###################
# Auto complete and linter
###################
# Surroundings: for example parentheses, brackets, quotes, XML tags, and more.
[[plugins]]
repo = 'tpope/vim-surround'

# Asynchronous Lint Engine, error check
[[plugins]]
repo = 'dense-analysis/ale'

# Auto complete
# [[plugins]]
# repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
merged = '0'

[[plugins]]
repo = 'mattn/vim-goimports'
