name: Docker image CI

on:
  push:
    paths:
      - nvim.dockerfile
      - .github/workflows/docker_image_ci.yml
      - config/dependencies/requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64
      - name: Build the Docker image
        run: |
          docker network create my-nvim
          docker compose up -d
