name: Lint-Dockerfile

on:
  push:
    branches:
      - mani
      - feature/*
    paths:
      - nvim.dockerfile
      - .github/workflows/lint_dockerfile.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: nvim.dockerfile
